name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run specific spec(s)
        default: cypress/e2e/*

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        browser: [electron, chrome, firefox]

    container:
      image: cypress/browsers:node-24.15.0-chrome-147.0.7727.101-1-ff-150.0-edge-147.0.3912.60-1
      options: --user 1001

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browser }}
          record: true
          parallel: true
          group: UI-${{ matrix.browser }}
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}