name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-electron-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.7

      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:
          install-command: npm install
          browser: electron
          record: true
          group: UI Electron
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: 0ab91200-4c1a-4902-8868-8d384d46bab8
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}